#!/usr/bin/env python3
"""Carry the current decisions from this knowledge base into a code repository.

The knowledge base holds the decisions — the system boundary, the module map, why a thing
was settled the way it was. The code lives in a different repository, and an agent opened
there reads that repository only. Without a bridge it builds a module on a boundary nobody
gave it.

This script is the bridge. It collects every `accepted` decision from the configured
sources and writes them as ONE generated file inside the code repository, at a path the
coding agent loads by itself when a session starts (default:
`.claude/rules/knowledge-base-decisions.md` — Claude Code reads every file in
`.claude/rules/` at startup, no import line needed).

Three properties are deliberate:

  explicit  It runs when somebody runs it — `/sync-decisions` or this script. No hook, no
            watcher, no CI job: the person working knows exactly when the code repository
            learnt about a decision, because they are the one who carried it across.
  one-way   The knowledge base stays the source of truth. The code repository receives a
            reflection, marked as generated. An edit made there is overwritten on the next
            run — the file says so at the top, to the human and to the agent.
  owned     The script writes exactly one file and nothing else in the code repository. It
            refuses to overwrite a file at that path that it did not generate, so pointing
            it at somebody's own notes loses nothing.

A decision is a Markdown file in `<source>/decisions/` with a YAML header (see
`CLAUDE.md` -> "Decisions"). Only `status: accepted` is carried across — a proposal is not
yet a decision, and a superseded one is exactly what the code must stop following. A
malformed decision file stops the run before anything is written: a reflection that
silently misses one decision looks identical to a complete one.

Usage:
    python tools/decisions-bridge/bridge.py                      # every target in the config
    python tools/decisions-bridge/bridge.py --target erp         # one configured target
    python tools/decisions-bridge/bridge.py --repo ../erp --source context/projects/ERP
    python tools/decisions-bridge/bridge.py --check              # compare, write nothing
    python tools/decisions-bridge/bridge.py --dry-run            # print what would be written

Relative paths — in the config and on the command line — resolve against the knowledge
base root, never the working directory, so the same config works from any shell and on
any operating system.

Exit: 0 when every target is written or already current; 1 when `--check` finds a target
out of date; 2 on a usage, config or decision-file error (nothing is written).
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover - environment guard
    print("[!] PyYAML is required: pip install pyyaml", file=sys.stderr)
    sys.exit(2)

DEFAULT_CONFIG = Path(__file__).resolve().parent / "config.yaml"
DEFAULT_OUTPUT = ".claude/rules/knowledge-base-decisions.md"
DECISIONS_DIR = "decisions"

STATUSES = ("proposed", "accepted", "superseded")
EXPORTED = "accepted"
REQUIRED_FIELDS = ("title", "status", "date")

# The first line of every generated file. It is how the script recognises its own output
# and refuses to overwrite anything else, so it must never change between versions
# without also accepting the old form.
MARKER = "<!-- GENERATED by the knowledge-base decisions bridge. Do not edit by hand. -->"
TARGET_NAME_RE = re.compile(r"^[A-Za-z0-9._-]+$")


class BridgeError(Exception):
    """A problem that must stop the run before anything is written."""


@dataclass(frozen=True)
class Decision:
    source: str      # source directory, relative to the knowledge base root (posix)
    slug: str        # file name without .md
    title: str
    status: str
    date: str        # YYYY-MM-DD
    body: str


@dataclass(frozen=True)
class Target:
    name: str
    repo: Path
    sources: tuple[str, ...]
    output: str


# ---------------------------------------------------------------------------- helpers

def default_root() -> Path:
    """Knowledge base root per git, falling back to the working directory."""
    try:
        out = subprocess.run(["git", "rev-parse", "--show-toplevel"],
                             capture_output=True, text=True, check=True)
        return Path(out.stdout.strip()).resolve()
    except (OSError, subprocess.CalledProcessError):
        return Path.cwd().resolve()


def resolve(root: Path, raw: str) -> Path:
    """Resolve a configured path: `~` expanded, relative paths anchored at the KB root."""
    path = Path(raw).expanduser()
    return (path if path.is_absolute() else root / path).resolve()


def as_date(value) -> str | None:
    if isinstance(value, datetime):
        return value.date().isoformat()
    if isinstance(value, date):
        return value.isoformat()
    if isinstance(value, str) and re.fullmatch(r"\d{4}-\d{2}-\d{2}", value.strip()):
        return value.strip()
    return None


# ---------------------------------------------------------------------------- reading

def parse_decision(path: Path, source: str, problems: list[str]) -> Decision | None:
    shown = f"{source}/{DECISIONS_DIR}/{path.name}"
    text = path.read_text(encoding="utf-8").replace("\r\n", "\n")
    if not text.startswith("---\n"):
        problems.append(f"{shown}: no YAML header")
        return None
    end = text.find("\n---", 4)
    if end == -1:
        problems.append(f"{shown}: unterminated YAML header")
        return None
    try:
        header = yaml.safe_load(text[4:end])
    except yaml.YAMLError as exc:
        problems.append(f"{shown}: YAML error — {exc}")
        return None
    if not isinstance(header, dict):
        problems.append(f"{shown}: YAML header is not a mapping of fields")
        return None

    missing = [f for f in REQUIRED_FIELDS if header.get(f) in (None, "")]
    if missing:
        problems.append(f"{shown}: missing required field(s) {', '.join(missing)}")
        return None
    status = str(header["status"]).strip()
    if status not in STATUSES:
        problems.append(f"{shown}: status '{status}' is not one of {', '.join(STATUSES)}")
        return None
    when = as_date(header["date"])
    if when is None:
        problems.append(f"{shown}: date must be YYYY-MM-DD")
        return None
    if status == "superseded" and not header.get("superseded_by"):
        problems.append(f"{shown}: superseded without superseded_by — name the decision "
                        "that replaced it")
        return None

    body = text[end + len("\n---"):].lstrip("\n").rstrip() + "\n"
    return Decision(source=source, slug=path.stem, title=str(header["title"]).strip(),
                    status=status, date=when, body=body)


def collect(root: Path, sources: tuple[str, ...]) -> list[Decision]:
    """Every decision in the sources, validated. Raises on any malformed file."""
    problems: list[str] = []
    decisions: list[Decision] = []
    for raw in sources:
        src_dir = resolve(root, raw)
        try:
            shown = src_dir.relative_to(root).as_posix() or "."
        except ValueError:
            raise BridgeError(f"source '{raw}' lies outside the knowledge base ({root})")
        if not src_dir.is_dir():
            raise BridgeError(f"source '{raw}' does not exist ({src_dir})")
        dec_dir = src_dir / DECISIONS_DIR
        if not dec_dir.is_dir():
            # An entity without decisions yet is normal; say so instead of failing.
            print(f"  note: {shown}/{DECISIONS_DIR}/ does not exist yet — no decisions from it",
                  file=sys.stderr)
            continue
        for path in sorted(dec_dir.glob("*.md")):
            if path.name.startswith("_"):  # _template.md, _index.md — not decisions
                continue
            decision = parse_decision(path, shown, problems)
            if decision:
                decisions.append(decision)
    if problems:
        raise BridgeError("malformed decision file(s), nothing written:\n    "
                          + "\n    ".join(problems))
    return decisions


# ---------------------------------------------------------------------------- rendering

def demote(body: str) -> str:
    """Push the decision's own headings two levels down, so they nest under its `###`.

    Fenced code is left alone — a `#` there is a comment, not a heading.
    """
    out, fence = [], None
    for line in body.split("\n"):
        stripped = line.lstrip()
        if stripped.startswith(("```", "~~~")):
            mark = stripped[:3]
            fence = None if fence == mark else (fence or mark)
        elif fence is None and re.match(r"#{1,4} ", line):
            line = "##" + line
        out.append(line)
    return "\n".join(out)


def render(kb_name: str, decisions: list[Decision]) -> str:
    """The generated file. Deterministic: the same decisions always give the same bytes,
    so re-running with nothing changed leaves the code repository's git status clean."""
    accepted = sorted((d for d in decisions if d.status == EXPORTED),
                      key=lambda d: (d.source, d.date, d.slug))
    lines = [
        MARKER,
        "",
        "# Decisions from the knowledge base",
        "",
        f"> **Generated file — do not edit here.** The source of truth is the knowledge base "
        f"`{kb_name}`; this file is its reflection, rewritten in full by "
        "`/sync-decisions` there. An edit made here is lost on the next run.",
        ">",
        "> Treat every decision below as settled. If the code you are asked to write "
        "contradicts one, stop and say so instead of working around it — changing a "
        "decision is done in the knowledge base, then carried here again.",
        "",
    ]
    if not accepted:
        lines += ["_No accepted decisions yet._", ""]
        return "\n".join(lines)

    lines += [f"{len(accepted)} accepted decision(s).", ""]
    current = None
    for d in accepted:
        if d.source != current:
            current = d.source
            lines += [f"## {current}", ""]
        lines += [f"### {d.title}", "",
                  f"_Accepted {d.date} · `{d.source}/{DECISIONS_DIR}/{d.slug}.md`_", "",
                  demote(d.body).rstrip(), ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------- targets

def load_targets(root: Path, config_path: Path) -> list[Target]:
    if not config_path.is_file():
        raise BridgeError(f"config not found: {config_path}")
    try:
        cfg = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError as exc:
        raise BridgeError(f"config {config_path} is not valid YAML — {exc}")
    raw_targets = cfg.get("targets") or []
    if not isinstance(raw_targets, list):
        raise BridgeError(f"config {config_path}: 'targets' must be a list")
    targets, seen = [], set()
    for i, t in enumerate(raw_targets, 1):
        if not isinstance(t, dict):
            raise BridgeError(f"config: target #{i} is not a mapping")
        name = str(t.get("name") or "").strip()
        if not TARGET_NAME_RE.match(name):
            raise BridgeError(f"config: target #{i} needs a 'name' (letters, digits, . _ -)")
        if name in seen:
            raise BridgeError(f"config: target name '{name}' is used twice")
        seen.add(name)
        if not t.get("repo"):
            raise BridgeError(f"config: target '{name}' has no 'repo'")
        sources = t.get("sources") or []
        if isinstance(sources, str):
            sources = [sources]
        if not sources:
            raise BridgeError(f"config: target '{name}' lists no 'sources'")
        targets.append(Target(name=name, repo=resolve(root, str(t["repo"])),
                              sources=tuple(str(s) for s in sources),
                              output=str(t.get("output") or DEFAULT_OUTPUT)))
    return targets


def output_path(target: Target) -> Path:
    out = Path(target.output)
    if out.is_absolute() or ".." in out.parts:
        raise BridgeError(f"target '{target.name}': output must be a path inside the code "
                          f"repository, got '{target.output}'")
    return target.repo / out


def sync(root: Path, target: Target, mode: str) -> str:
    """Write (or check, or print) one target. Returns 'written', 'current' or 'stale'."""
    if not target.repo.is_dir():
        raise BridgeError(f"target '{target.name}': code repository not found at "
                          f"{target.repo}")
    if target.repo == root:
        raise BridgeError(f"target '{target.name}': the code repository is this knowledge "
                          "base itself — point 'repo' at the other repository")
    dest = output_path(target)
    content = render(root.name, collect(root, target.sources))

    existing = dest.read_text(encoding="utf-8") if dest.is_file() else None
    if existing is not None:
        existing = existing.replace("\r\n", "\n")
        if not existing.startswith(MARKER):
            raise BridgeError(f"target '{target.name}': {dest} exists and was not generated "
                              "by this bridge — refusing to overwrite it. Move it, or set "
                              "a different 'output'.")
    if mode == "dry-run":
        print(content)
        return "current" if existing == content else "stale"
    if existing == content:
        return "current"
    if mode == "check":
        return "stale"
    dest.parent.mkdir(parents=True, exist_ok=True)
    # newline="\n": the same bytes on Windows and POSIX, so a teammate on the other
    # system does not see the whole file as changed.
    with open(dest, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(content)
    return "written"


# ---------------------------------------------------------------------------- CLI

def main(argv: list[str] | None = None) -> int:
    # A Windows console defaults to a legacy code page; decisions are rarely ASCII-only.
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8")
        except (AttributeError, ValueError):
            pass
    parser = argparse.ArgumentParser(
        description="Carry accepted decisions from this knowledge base into a code repository.")
    parser.add_argument("--root", help="knowledge base root (default: git toplevel)")
    parser.add_argument("--config", help=f"bridge config (default: {DEFAULT_CONFIG.name} "
                                         "next to this script)")
    parser.add_argument("--target", action="append", default=[],
                        help="run only this configured target (repeatable)")
    parser.add_argument("--repo", help="code repository path — an ad-hoc target instead of "
                                       "the config")
    parser.add_argument("--source", action="append", default=[],
                        help="with --repo: a directory whose decisions/ is carried across "
                             "(repeatable)")
    parser.add_argument("--output", default=DEFAULT_OUTPUT,
                        help=f"with --repo: file inside the code repository "
                             f"(default: {DEFAULT_OUTPUT})")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true",
                      help="write nothing; exit 1 if any target is out of date")
    mode.add_argument("--dry-run", action="store_true",
                      help="print what would be written, write nothing")
    args = parser.parse_args(argv)

    root = Path(args.root).resolve() if args.root else default_root()
    run_mode = "check" if args.check else "dry-run" if args.dry_run else "write"

    try:
        if args.repo:
            if args.target:
                raise BridgeError("--repo and --target are two ways to name a target; "
                                  "use one")
            if not args.source:
                raise BridgeError("--repo needs at least one --source")
            targets = [Target(name="ad-hoc", repo=resolve(root, args.repo),
                              sources=tuple(args.source), output=args.output)]
        else:
            config = resolve(root, args.config) if args.config else DEFAULT_CONFIG
            targets = load_targets(root, config)
            if args.target:
                unknown = sorted(set(args.target) - {t.name for t in targets})
                if unknown:
                    raise BridgeError(f"unknown target(s): {', '.join(unknown)} — "
                                      f"configured: {', '.join(t.name for t in targets) or 'none'}")
                targets = [t for t in targets if t.name in args.target]
            if not targets:
                raise BridgeError(f"no targets configured in {config} — add one, or pass "
                                  "--repo PATH --source DIR")

        stale = 0
        for target in targets:
            result = sync(root, target, run_mode)
            dest = output_path(target)
            label = {"written": "WRITTEN", "current": "UP TO DATE",
                     "stale": "OUT OF DATE"}[result]
            # In a dry run stdout carries the file itself, so the verdict goes to stderr.
            stream = sys.stderr if run_mode == "dry-run" else sys.stdout
            print(f"  {label}: {target.name} -> {dest}", file=stream)
            stale += result == "stale"
    except BridgeError as exc:
        print(f"[!] {exc}", file=sys.stderr)
        return 2

    if run_mode == "check" and stale:
        print(f"{stale} target(s) out of date — run /sync-decisions to carry them across")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
