"""Tests for bridge.py — run with `python -m unittest tools/decisions-bridge/test_bridge.py`."""

import contextlib
import io
import os
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bridge  # noqa: E402

ENTITY = "context/projects/ALPHA"
OUT = Path(".claude/rules/knowledge-base-decisions.md")


def decision(title, status="accepted", when="2026-09-01", body="Body.\n", extra=""):
    return f'---\ntitle: "{title}"\nstatus: {status}\ndate: {when}\n{extra}---\n\n{body}'


class BridgeTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        base = Path(self.tmp.name)
        self.kb = base / "kb"
        self.code = base / "code"
        self.code.mkdir(parents=True)
        self.write(f"{ENTITY}/decisions/boundary.md",
                   decision("System boundary", body="## Why\n\nPayroll stays outside.\n"
                            "```sh\n# not a heading\n```\n"))
        self.write(f"{ENTITY}/decisions/older.md", decision("Old choice", when="2026-08-01"))
        self.write(f"{ENTITY}/decisions/idea.md", decision("Just an idea", status="proposed"))
        self.write(f"{ENTITY}/decisions/replaced.md",
                   decision("Replaced choice", status="superseded",
                            extra="superseded_by: boundary\n"))
        self.write(f"{ENTITY}/decisions/_template.md", "not a decision")

    def tearDown(self):
        self.tmp.cleanup()

    def write(self, rel, text):
        path = self.kb / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")

    def run_bridge(self, *args):
        out, err = io.StringIO(), io.StringIO()
        with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
            code = bridge.main(["--root", str(self.kb), *args])
        return code, out.getvalue(), err.getvalue()

    def adhoc(self, *extra):
        return self.run_bridge("--repo", "../code", "--source", ENTITY, *extra)

    def generated(self):
        return (self.code / OUT).read_text(encoding="utf-8")

    def test_writes_only_accepted_decisions_in_date_order(self):
        code, out, _ = self.adhoc()
        self.assertEqual(code, 0, out)
        text = self.generated()
        self.assertTrue(text.startswith(bridge.MARKER))
        self.assertIn("2 accepted decision(s).", text)
        self.assertLess(text.index("Old choice"), text.index("System boundary"))
        for absent in ("Just an idea", "Replaced choice", "not a decision"):
            self.assertNotIn(absent, text)

    def test_headings_nest_under_the_decision_but_code_is_untouched(self):
        self.adhoc()
        text = self.generated()
        self.assertIn("\n#### Why\n", text)
        self.assertIn("\n# not a heading\n", text)

    def test_second_run_is_a_no_op_and_check_agrees(self):
        self.adhoc()
        first = (self.code / OUT).read_bytes()
        code, out, _ = self.adhoc()
        self.assertIn("UP TO DATE", out)
        self.assertEqual((self.code / OUT).read_bytes(), first)
        self.assertEqual(self.adhoc("--check")[0], 0)
        self.assertNotIn(b"\r\n", first)

    def test_check_reports_a_new_decision_and_writes_nothing(self):
        self.adhoc()
        before = self.generated()
        self.write(f"{ENTITY}/decisions/new.md", decision("Fresh one", when="2026-09-20"))
        code, out, _ = self.adhoc("--check")
        self.assertEqual(code, 1)
        self.assertIn("OUT OF DATE", out)
        self.assertEqual(self.generated(), before)

    def test_refuses_to_overwrite_a_file_it_did_not_generate(self):
        (self.code / OUT).parent.mkdir(parents=True)
        (self.code / OUT).write_text("my own notes\n", encoding="utf-8")
        code, _, err = self.adhoc()
        self.assertEqual(code, 2)
        self.assertIn("not generated by this bridge", err)
        self.assertEqual(self.generated(), "my own notes\n")

    def test_a_malformed_decision_stops_the_run_before_writing(self):
        self.write(f"{ENTITY}/decisions/broken.md", decision("Broken", status="maybe"))
        self.write(f"{ENTITY}/decisions/orphaned.md",
                   decision("No successor", status="superseded"))
        code, _, err = self.adhoc()
        self.assertEqual(code, 2)
        self.assertIn("broken.md: status 'maybe'", err)
        self.assertIn("orphaned.md: superseded without superseded_by", err)
        self.assertFalse((self.code / OUT).exists())

    def test_config_targets_resolve_against_the_kb_root(self):
        self.write("tools/decisions-bridge/config.yaml",
                   f"targets:\n  - name: erp\n    repo: ../code\n    sources: [{ENTITY}]\n"
                   "    output: docs/DECISIONS.md\n")
        cwd = os.getcwd()
        os.chdir(self.tmp.name)  # anywhere but the KB root
        try:
            code, out, _ = self.run_bridge("--config", "tools/decisions-bridge/config.yaml",
                                           "--target", "erp")
        finally:
            os.chdir(cwd)
        self.assertEqual(code, 0, out)
        self.assertTrue((self.code / "docs/DECISIONS.md").is_file())

    def test_bad_targets_are_refused(self):
        self.assertEqual(self.run_bridge("--repo", "../missing", "--source", ENTITY)[0], 2)
        self.assertEqual(self.run_bridge("--repo", ".", "--source", ENTITY)[0], 2)
        self.assertEqual(self.adhoc("--output", "../escape.md")[0], 2)
        self.assertEqual(self.run_bridge("--repo", "../code")[0], 2)
        self.write("empty.yaml", "targets: []\n")
        code, _, err = self.run_bridge("--config", "empty.yaml")
        self.assertEqual(code, 2)
        self.assertIn("no targets configured", err)

    def test_a_source_without_decisions_yields_an_empty_reflection(self):
        self.write("context/projects/BETA/project.md", "# BETA\n")
        code, _, _ = self.run_bridge("--repo", "../code", "--source", "context/projects/BETA")
        self.assertEqual(code, 0)
        self.assertIn("_No accepted decisions yet._", self.generated())


if __name__ == "__main__":
    unittest.main()
